apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  traefik.toml: |
    # traefik.toml
    [entrypoints]
      [entrypoints.http]
        address = ":8880"

      [entrypoints.https]
        address = ":8443"

        [entrypoints.web-secure.tls]

    [providers]
    [providers.kubernetescrd]
